name: Validate Terraform

on:
  pull_request:
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read

jobs:
  validate-format:
    runs-on: ubuntu-latest
    name: Terraform Format Check
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
      - name: Validate Terraform Format
        run: terraform fmt -check -recursive

  validate-syntax:
    runs-on: ubuntu-latest
    name: Terraform Validation
    needs: validate-format
    steps:
      - uses: actions/checkout@v3
      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
